### PR TITLE
Code style fixes

### PR DESCRIPTION
**Pull request by krzysztof-gzocha**

### CODE REVIEW

**Comment by medinae** [comment]
amazing code.

**Comment by krzysztof-gzocha** [comment]
Thank you. It is nice to hear it :)

**Comment by medinae** [comment]
If you work on a personnal Symfony project and need a 2nd developer, do not hesitate to mail me at : 
ak.bouadjadja@gmail.com

**Comment by krzysztof-gzocha** [comment]
I'm trying to constantly improve Searcher and **[SearcherBundle](https://github.com/krzysztof-gzocha/searcher-bundle)** which is will ease integration between Symfony framework and this library. If you have any idea how to make it better, please send a pull-request. There are some issues posted on GitHub - you can check them. For example: https://github.com/krzysztof-gzocha/searcher-bundle/issues/20 I think it might be useful, but I didn't figure this out completely how it should work. If you have any idea please comment there :)

I will let you know about my any further Symfony-based projects.

**Comment by krzysztof-gzocha** [comment]
@medinae Maybe you can take care of #29 ? What do you think?

**Comment by medinae** [comment]
Hi Krysztof,

I'm very interested. I'm now out of Paris (my home) but i will be back tonight.

I will analyze #29 and you'll hear from me.

Thank.

**Comment by krzysztof-gzocha** [comment]
Ok. Thanks. Let's move the conversation to the issue #29 :)

**Pull request merged**
