### PR TITLE
Feature/doctrine result cache adapter

### PR DESCRIPTION
**Pull request by medinae**
Allow result caching through a new searching context.

### CODE REVIEW

**Comment by medinae** [comment]
Some issues with phpunit and my environement here @work. 
Let's push the unit tests tonight or this week end, my lunch break is finish, i've to go :)

**Comment by krzysztof-gzocha** [comment]
I'm now just thinking what if someone would like to enable both: query and result caching? We would need to add 3rd class just for this scenario? I doesn't look fine for me.

What do you @medinae and @drgomesp think about having 1 SearchingContext for Doctrine's ORM with 2 additional flags (and setters), which could configure those parameters?

I'll open new PR with some example code..

**Comment by medinae** [comment]
It can be better. Let's see your PR.

**Comment by krzysztof-gzocha** [comment]
Hmm.. but.. If I will implement a special SearchingContext just to configure QueryBuilder inside it would it be a solid code? I guess we all can pass already configured QueryBuilder with the proper settings of caching to `\KGzocha\Searcher\Context\Doctrine\QueryBuilderSearchingContext` and `CachedQueryBuilderSearchingContext` is not really needed.

What do you think?

**Comment by medinae** [comment]
I think it depends on everyone's preference. We can implement our cached searching context and stay solid. For my part, as a Searcher user, i prefer to have my specific cached context and to deal with it. The developers are lazy, let's make their work easy ahah

**Comment by krzysztof-gzocha** [comment]
I agree with making life easier, but I was thinking about 1 config file with result cache flag, cache driver, caching TTL, result cache flag, result cache driver, caching key, etc. Creating all this logic to just pass it to QueryBuilder is not making much sense for me, because developer will need to get those flags and parameters either way, right?

So by default he can use normal SearchingContext and when he need a caching he will just construct it with properly build QueryBuilder

**Comment by medinae** [comment]
Good idea. If you can open a new PR with some description, it'll be amazing !

**Comment by krzysztof-gzocha** [comment]
Done in #88
I think thats all we can do about caching and issue #29 will be closed.

**Comment by krzysztof-gzocha** [comment]
As in #88 caching contexts are removed this one does not make sense, so I'm closing it.
Either way thanks for your time.

**Pull request closed without merging**
